= Build your own ZK game

== 🤔 What are we building?

[abstract]
We will build a zero-knowledge game "zk-HiLo" using Poseidon's zk-sdk. 
Zk-HiLo is intended as a 'Hello World' example for using the Poseidon Labs zkShuffle contracts.
This repo contains a set of contracts and a frontend web app for playing an on-chain, zk-Powered game of Hi-Lo against a server.

== ⚙️ Environment Setup

[sectnumlevels=3]
Our tech stack would be composed of Next.js for front-end, and hardhat for local contract testing. 

=== 🗃️ Step 1: Download our sample code

[TODO]
Go to <Placeholder> to download latest code.

=== Step 2: Setup backend

[TODO]
* In the contracts directory:
[source,bash]
yarn install
npx hardhat node
npx hardhat run --network localhost scripts/deploy.ts


==== Subsection 2.1

[TODO]
Add content for Subsection 2.1 here.

==== Subsection 2.2

[TODO]
Add content for Subsection 2.2 here.

== Conclusion

[TODO]
Add conclusion text here.

== References

This section contains a list of all references cited in the document.

[TODO]
Add references here.
